# Generated by Django 5.2.7 on 2025-11-12 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=20)),
                ('service_details', models.TextField(blank=True, null=True)),
                ('advisor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('booked', 'Service Booked'), ('in_progress', 'In Progress'), ('completed', 'Service Completed'), ('ready', 'Ready for Pickup')], default='booked', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
