# Generated by Django 5.2.7 on 2025-12-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('fixed', 'Fixed Services'), ('flexible', 'Flexible Services')], default='flexible', max_length=20),
        ),
    ]
