# Generated by Django 5.2.7 on 2025-11-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0002_contactoption_faq_resource_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactoption',
            name='value',
        ),
        migrations.AddField(
            model_name='contactoption',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactoption',
            name='label',
            field=models.CharField(default='Chat with us', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactoption',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactoption',
            name='method',
            field=models.CharField(choices=[('chat', 'Chat with us'), ('call', 'Call us'), ('email', 'Email us')], max_length=10),
        ),
    ]
