# Generated by Django 5.2.7 on 2025-12-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0002_offer_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
