# Generated by Django 5.2.7 on 2025-11-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('ready_for_pickup', 'Ready for Pickup'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
        migrations.DeleteModel(
            name='ServiceBooking',
        ),
    ]
