# Generated by Django 5.2.7 on 2025-12-11 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0003_customer_notifications_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], max_length=20, unique=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='memberships/')),
                ('benefits', models.JSONField(default=dict, help_text="Ex: {'booking_discount':10, 'loyalty_bonus':2}")),
                ('duration_in_days', models.PositiveIntegerField(default=30)),
                ('welcome_points', models.PositiveIntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='StitchCarbackendapp.customer')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StitchCarbackendapp.membershipplan')),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='eligible_memberships',
            field=models.ManyToManyField(blank=True, help_text='Leave empty for all members.', to='StitchCarbackendapp.membershipplan'),
        ),
        migrations.AddField(
            model_name='offer',
            name='eligible_memberships',
            field=models.ManyToManyField(blank=True, help_text='Leave empty for all members.', to='StitchCarbackendapp.membershipplan'),
        ),
    ]
