# Generated by Django 5.2.7 on 2025-12-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0004_membershipplan_customermembership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='duration_in_days',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='duration_in_months',
            field=models.PositiveIntegerField(default=1, help_text='Membership validity in months'),
        ),
    ]
