# Generated by Django 5.2.7 on 2025-11-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0004_alter_booking_status_delete_servicebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(related_name='bookings', to='StitchCarbackendapp.service'),
        ),
    ]
