# Generated by Django 5.2.7 on 2025-12-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0005_remove_membershipplan_duration_in_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat'), ('free', 'Free')], default='percentage', help_text='Select whether this offer is percentage, flat, or free.', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='If percentage: 10.00 = 10%. If flat: 100 = ₹100. If free: keep 0.', max_digits=7),
        ),
    ]
