# Generated by Django 5.2.7 on 2025-11-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0005_remove_booking_service_booking_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='interval_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
