# Generated by Django 5.2.7 on 2025-11-18 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0006_alter_booking_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='promotion_banners/')),
                ('button_text', models.CharField(default='Book Now', max_length=50)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='service',
        ),
        migrations.AddField(
            model_name='offer',
            name='services',
            field=models.ManyToManyField(related_name='offers', to='StitchCarbackendapp.service'),
        ),
        migrations.CreateModel(
            name='FeaturedPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_text', models.CharField(default='View Details', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_promotions', to='StitchCarbackendapp.offer')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
