# Generated by Django 5.2.7 on 2025-11-18 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0007_coupon_appliedcoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('recall_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('urgency', models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('moderate', 'Moderate')], default='moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='StitchCarbackendapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRecall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled')], default='active', max_length=20)),
                ('last_service_date', models.DateTimeField(blank=True, null=True)),
                ('next_service_date', models.DateTimeField(blank=True, null=True)),
                ('service_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_recalls', to='StitchCarbackendapp.recall')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_recalls', to='StitchCarbackendapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RecallServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_repeat_service', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_services', to='StitchCarbackendapp.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_services', to='StitchCarbackendapp.customer')),
                ('vehicle_recall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='StitchCarbackendapp.vehiclerecall')),
            ],
        ),
    ]
