# Generated by Django 5.2.7 on 2025-11-19 11:13

import StitchCarbackendapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0007_promotionbanner_remove_offer_service_offer_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('registered', 'Registered'), ('completed', 'Completed First Booking')], default='invited', max_length=20)),
                ('reward_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(default=StitchCarbackendapp.models.generate_referral_code, max_length=20, unique=True)),
                ('invited_count', models.IntegerField(default=0)),
                ('rewards_earned', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
