# Generated by Django 5.2.7 on 2025-11-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0008_recall_vehicle_vehiclerecall_recallservicehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recall',
            name='affected_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recall',
            name='affected_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recall',
            name='year_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recall',
            name='year_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
