# Generated by Django 5.2.7 on 2025-11-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0008_referralactivity_referralprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='StitchCarbackendapp.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vin'], name='StitchCarba_vin_30f014_idx'), models.Index(fields=['vehicle_number'], name='StitchCarba_vehicle_25c5fd_idx'), models.Index(fields=['make', 'model', 'year'], name='StitchCarba_make_32f20e_idx')],
            },
        ),
    ]
