# Generated by Django 5.2.7 on 2025-11-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0010_booking_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
