# Generated by Django 5.2.7 on 2025-11-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0010_alter_vehicle_options_vehicle_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recall',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Select the existing service this recall is related to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recalls', to='StitchCarbackendapp.service'),
        ),
    ]
