# Generated by Django 5.2.7 on 2025-11-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0011_booking_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpromotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_promotions/'),
        ),
    ]
