# Generated by Django 5.2.7 on 2025-11-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0011_recall_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_recall_service',
            field=models.BooleanField(default=False),
        ),
    ]
