# Generated by Django 5.2.7 on 2025-11-20 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0012_booking_is_recall_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StitchCarbackendapp.reward'),
        ),
        migrations.AddField(
            model_name='reward',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='StitchCarbackendapp.service'),
        ),
    ]
