# Generated by Django 5.2.7 on 2025-11-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0012_featuredpromotion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpromotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
