# Generated by Django 5.2.7 on 2025-11-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0013_booking_reward_reward_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningrule',
            name='amount_base',
            field=models.IntegerField(default=0),
        ),
    ]
