# Generated by Django 5.2.7 on 2025-11-21 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0013_featuredpromotion_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionbanner',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_banners', to='StitchCarbackendapp.offer'),
        ),
    ]
