# Generated by Django 5.2.7 on 2025-11-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0014_earningrule_amount_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['required_points']},
        ),
        migrations.AddField(
            model_name='reward',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text="For 'discount' use 0.10 for 10%. For flat/cashback use ₹ value.", max_digits=10),
        ),
        migrations.AddField(
            model_name='reward',
            name='type',
            field=models.CharField(choices=[('free', 'Free Service'), ('discount', 'Discount (%) or ₹'), ('flat', 'Flat ₹ Off'), ('cashback', 'Cashback (₹)')], default='free', help_text='Type of reward: Free, Discount, Flat, or Cashback', max_length=20),
        ),
    ]
