# Generated by Django 5.2.7 on 2025-11-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0014_promotionbanner_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpromotion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredpromotion',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
