# Generated by Django 5.2.7 on 2025-11-22 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0015_alter_reward_options_reward_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='earning_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StitchCarbackendapp.earningrule'),
        ),
        migrations.AddField(
            model_name='booking',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='earningrule',
            name='min_spend',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum spend to qualify for points (optional).', max_digits=10, null=True),
        ),
    ]
