# Generated by Django 5.2.7 on 2025-11-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0015_featuredpromotion_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpromotion',
            name='promo_type',
            field=models.CharField(choices=[('all', 'General Users'), ('new', 'New Customers'), ('inactive', 'Inactive Customers'), ('loyal', 'Loyal Customers')], default='all', max_length=20),
        ),
    ]
