# Generated by Django 5.2.7 on 2025-11-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0017_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveSmallIntegerField(default=0)),
                ('punctuality_rating', models.PositiveSmallIntegerField(default=0)),
                ('service_quality_rating', models.PositiveSmallIntegerField(default=0)),
                ('communication_rating', models.PositiveSmallIntegerField(default=0)),
                ('review', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='StitchCarbackendapp.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_feedbacks', to='StitchCarbackendapp.customer')),
            ],
            options={
                'unique_together': {('customer', 'booking')},
            },
        ),
    ]
