# Generated by Django 5.2.8 on 2025-11-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StitchCarbackendapp', '0016_featuredpromotion_promo_type'),
        ('StitchCarbackendapp', '0018_servicefeedback'),
    ]

    operations = [
    ]
